import { Outfit } from "next/font/google";
import "./globals.css";
// import { ToastContainer } from "react-toastify";
// import 'react-toastify/dist/ReactToastify.css';


const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400","500","600","700","800"]
});



export const metadata = {
  title: "My Book List",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        {/* <ToastContainer/> */}
        {children}
      </body>
    </html>
  );
}
